# CONFIG FOR request-info
requestInfoReplyComment:
  - We would appreciate it if you could provide us with more info about this issue/pr!
  - Please tell me more!
  - I'm sure you can be more effusive!

requestInfoLabelToAdd: needs-more-info
requestInfoOn:
  pullRequest: true
  issue: true

requestInfoUserstoExclude:
  - a01sa01to