automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 2

env: standard
instance_class: F1
runtime: php73

handlers:
  - url: /.*
    secure: always
    script: auto