version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: Change Directory
          command: cd blog
      - run:
          name: Update npm
          command: 'sudo npm i -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "blog/package-lock.json" }}
      - run:
          name: Install deps
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "blog/package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm build